name: Swift Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test